name: Pylint
on:
  push:
    branches: 
      - master

jobs:
  codestyle:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Preparing Checks
      id: prep
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint pylint-exit

    - name: Checks
      id: pylint
      run: python -m pylint -f colorized hanser_py_library || python -m pylint-exit -efail -wfail $?